# Generated by Django 4.1.7 on 2023-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofundus',
            name='class_name',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
