# Generated by Django 4.1.7 on 2023-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ofundus_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofundus',
            name='class_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
