# Generated by Django 4.1.7 on 2023-03-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ofundus_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofundus',
            name='name',
        ),
    ]
