# Generated by Django 4.1.7 on 2023-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ofundus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofundus',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='Images/'),
        ),
    ]
