# Generated by Django 4.1.7 on 2023-03-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ofundus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofundus',
            name='check_for_macular_edema',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ofundus',
            name='refer_to_hospital',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ofundus',
            name='class_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
